apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
      - name: task-tracker
        image: your-docker-repo/task-tracker:latest
        ports:
        - containerPort: 3000
