name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Deploy
        run: |
          cd client
          npm install
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
